name: Organization Metrics

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # =============================
      # EngineeringSebastian-s
      # =============================
      - name: EngineeringSebastian-s
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics/orgs/metrics.engineeringsebastians.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: EngineeringSebastian-s
          base: header, activity, community, repositories, metadata
          config_timezone: America/Bogota

      # =============================
      # PepperTechDev
      # =============================
      - name: PepperTechDev
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics/orgs/metrics.peppertechdev.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: PepperTechDev
          base: header, activity, community, repositories, metadata
          config_timezone: America/Bogota

      # =============================
      # SmartPotTech
      # =============================
      - name: SmartPotTech
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics/orgs/metrics.smartpottech.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: SmartPotTech
          base: header, activity, community, repositories, metadata
          config_timezone: America/Bogota

      # =============================
      # TaurusSebastian-s
      # =============================
      - name: TaurusSebastian-s
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics/orgs/ metrics.org.taurussebastians.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: TaurusSebastian-s
          base: header, activity, community, repositories, metadata
          config_timezone: America/Bogota

      # =============================
      # TechnicalSebastians
      # =============================
      - name: TechnicalSebastians
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics/orgs/metrics.technicalsebastians.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: TechnicalSebastians
          base: header, activity, community, repositories, metadata
          config_timezone: America/Bogota


      # =============================
      # VocationalSebastian-s
      # =============================
      - name: VocationalSebastian-s
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics/orgs/metrics.vocationalsebastians.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: VocationalSebastian-s
          base: header, activity, community, repositories, metadata
          config_timezone: America/Bogota

      # =============================
      # TestLabData
      # =============================
      - name: TestLabData
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics/orgs/metrics.testlabdata.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: TestLabData
          base: header, activity, community, repositories, metadata
          config_timezone: America/Bogota

      # =============================
      # TivenosEducation
      # =============================
      - name: TivenosEducation
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics/orgs/metrics.tivenoseducation.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: TivenosEducation
          base: header, activity, community, repositories, metadata
          config_timezone: America/Bogota

      # =============================
      #  ADCOM-Group
      # =============================
      - name: ADCOM-Group
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics/orgs/metrics.adcom-group.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ADCOM-Group
          base: header, activity, community, repositories, metadata
          config_timezone: America/Bogota


