name: Organization Metrics

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # =============================
      # üè¢ EngineeringSebastian-s
      # =============================
      - name: EngineeringSebastian-s
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.org.engineeringsebastians.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: EngineeringSebastian-s
          base: header, activity, community, repositories
          config_timezone: America/Bogota

      # =============================
      # üè¢ PepperTechDev
      # =============================
      - name: PepperTechDev
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.org.peppertechdev.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: PepperTechDev
          base: header, activity, community, repositories
          config_timezone: America/Bogota

      # =============================
      # üè¢ SmartPotTech
      # =============================
      - name: SmartPotTech
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.org.smartpottech.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: SmartPotTech
          base: header, activity, community, repositories
          config_timezone: America/Bogota

      # =============================
      # üè¢ TaurusSebastian-s
      # =============================
      - name: TaurusSebastian-s
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.org.taurussebastians.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: TaurusSebastian-s
          base: header, activity, community, repositories
          config_timezone: America/Bogota

      # =============================
      # üè¢ TechnicalSebastians
      # =============================
      - name: TechnicalSebastians
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.org.technicalsebastians.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: TechnicalSebastians
          base: header, activity, community, repositories
          config_timezone: America/Bogota


      # =============================
      # üè¢ VocationalSebastian-s
      # =============================
      - name: VocationalSebastian-s
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.org.vocationalsebastians.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: VocationalSebastian-s
          base: header, activity, community, repositories
          config_timezone: America/Bogota
